### ISSUE TITLE
Issues with Conda Environment Setup in envpy3.yml

### ISSUE THREAD

**Issue by laleoarrow** [rhhao/csMR#7]
Hi,

I encountered some issues while setting up the Conda environment using the provided envpy3.yml file. Specifically, I ran into dependency conflicts, particularly with r-twosamplemr and some R package versions.

To resolve the issue, I removed version constraints for the R packages and excluded r-twosamplemr from the yml file. I was then able to successfully create the environment and manually installed r-twosamplemr afterward.

Here’s the modified envpy3.yml that worked for me. I would like to ask if this approach is valid, or if the workflow requires specific versions of these packages for proper functionality?

```yaml
name: csMR

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.8
  - pybedtools
  - r-base=4.2.2
  - snakemake=7.18.2
  - r-getopt
  - r-meta
  - r-googleauthr
  - r-ieugwasr
  - r-susier
  - r-coloc
  - r-pkgload
```
